
# About this book {-}

The main goal of the "Reproducible data analysis in R" is to impart practical basic skills on biological data analysis in R, including data cleaning, tidying, normalization, transformation, visualization, modelling, and publication. 
The emphasis is on data analytic tools from **tidyverse** ecosystem that allow efficient and human readable data analytic workflows. 
No previous experience with the R language is required. 
While basic knowledge of statistics doesn't hurt, it is not necessary.

The reader will learn how to work with different data formats, she is able to create pleasing, informative publication quality visualizations, fit and interpret linear and logistic models, and to analyse her data in an effective and reproducible manner. 
She will also have basic skills in using the R functions best suited for biological data analysis and to program her own functions as needed.

We will cover for you the full workflow of data analysis, from inputting data to outputting the report, using simple-to-understand yet effective code. 
The course will include many hands-on tutorials with the possibility of using your own data. 
Emphasis will be on practical tips that make your data analysis more efficient, reproducible, and less painful. 

