---
title: Reproducible data analysis in R course
---

The main goal of the course is to impart practical basic skills on biological data analysis in R, including data cleaning, tidying, normalization, transformation, visualization, modelling, and publication. The emphasis is on data analytic tools created by Hadley Wickham that allow for simple and efficient data analytic workflows. The course does not assume prior experience with programming, R, or statistics.

The student will learn how to work with different data formats, she is able to create pleasing, informative publication quality visualizations, fit and interpret linear and logistic models, and to analyse her data in an effective and reproducible manner. She will also have basic skills in using the R functions best suited for biological data analysis and to program her own functions as needed.

We will cover for you the full workflow of data analysis, from inputting data to outputting the report, using simple-to-understand yet effective code. The course will include many hands-on tutorials with the possibility of using your own data. Emphasis will be on practical tips that make your data analysis more efficient, reproducible, and less painful. No previous experience with the R language is required. While basic knowledge of statistics doesn't hurt, it is not necessary.



Ülo Maiväli, PhD, associate professor, Institute of Technology, University of Tartu, Estonia. His research interests include applied Bayesian statistics, meta-science, and molecular biology of protein synthesis.

Taavi Päll, PhD, research fellow, Institute of Biological and Translational Medicine, University of Tartu, Estonia. His research interests include understanding the role of human gut virome in health and disease, computational reproducibility, applied Bayesian statistics. He is involved in Estonian Sars-Cov-2 sequencing project.
